## CIND830 - Python Programming for Data Science  
### Assignment 2 (10% of the final grade)
### Due on March 15, 2021 11:59 PM

*****
This is a Jupyter Notebook document that extends a simple formatting syntax for authoring HTML and PDF.
Review [this](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html) website for more details on using Juputer Notebook.

Use the JupyterHub server on the Google Cloud Platform, provided by your designated instructor, for this assignment. Ensure using Python 3.7.6 release then complete the assignment by inserting your Python code wherever seeing the string "#INSERT YOUR ANSWER HERE."

When you click the `File` button, from the top navigation bar, then select `Export Notebook As ...`,
a document (PDF or HTML format) will be generated that includes
 both the assignment content and the output of any embedded Python code chunks.

Using [these](https://www.ryerson.ca/courses/students/tutorials/assignments/) guidelines,
submit **both** the IPYNB and the exported file (PDF or HTML).
Failing to submit both files will be subject to mark deduction.

*****

### Question 1 **[50 pts]**:

**a)** **[15 pts]** Define a function called `isSymmetrical` that takes a string value as a parameter and returns `TRUE` if the given string is Symmetrical. A string is said to be symmetrical if the reverse of the string is the same as string. For example, “madam” is symmetrical, but “water” is not symmetrical.

In [25]:
#INSERT YOUR ANSWER HERE.

#user inputs string
x = str(input("Enter a word that is a palindrome:"))

#function reverses string and then applies logical check
def isSymmetrical (txt):
    return txt==(txt) [::-1]

print(isSymmetrical (x))

Enter a word that is a palindrome: water


False


**b)** **[5 pts]** Modify the `isSymmetrical` function you created in Q1.a to take any type of data as an input and return `TRUE` if the input is symmetrical. For example, "12321" is symmetrical, but "12345" is not symmetrical.

In [26]:
#INSERT YOUR ANSWER HERE.

#user inputs any data type
x1 = input("Enter any word or number to check:")

#function reverses variable and then applies logical check
def isSymmetrical (txt):
    return txt==(txt) [::-1]

print(isSymmetrical(x1))

Enter any word or number to check: water


False


**c)** **[10 pts]** Define a function called `isSymmetricalVec` that calls `isSymmetrical` function you updated in Q1.b to take a list of elements and return their results in a list.  For example, given \["1441", "Apple", "radar", "232", "plane"\] the function returns \[`TRUE`, `FALSE`, `TRUE`, `TRUE`, `FALSE`\]

In [29]:
#### INSERT YOUR ANSWER HERE.

#ask user for elements
elements = input("Enter word or numbers with spaces:")

def isSymmetricalVec (txt):
    #split elements on whitespace to save as list
    word1 = txt.split()
    #for-loop to check each word in our list word1 for defined function
    L1 = []
    for i in word1:
        y1= isSymmetrical(i)
        L1.append(y1)
    return L1
    
print(isSymmetricalVec(elements))

Enter word or numbers with spaces: 1441 Apple radar 232 plane


[True, False, True, True, False]


**d)** **[10 pts]** Define a function called `isSymmetricalDict` by modifying the function you created in Q1.c to return the results in a dictionary with their corresponding input elements. \
For example, given \["1441", "Apple", "radar", "232", "plane"\] the function returns {"1441": `TRUE`, "Apple": `FALSE`, "radar": `TRUE`, "232": `TRUE`, "plane": `FALSE`\}

In [42]:
# INSERT YOUR ANSWER HERE.

def isSymmetrical (txt):
    return txt==(txt) [::-1]

def isSymmetricalDict (elements):
    D1 = {}
    for i in elements:
        y1 = {i:isSymmetrical(i)}
        D1.update(y1)
    return D1

elements = input("Enter word or numbers with spaces:").split()

print(isSymmetricalDict(elements))

Enter word or numbers with spaces: 1441 Apple radar 232 plane


{'1441': True, 'Apple': False, 'radar': True, '232': True, 'plane': False}


**e)** **[10 pts]** Define a function called `isSymmetricalTuple` by modifying the function you created in Q1.d to traverse the values of the returned dictionary **in reverse order** and return the dictionary keys that has a **`TRUE`** value as a tuple.  For example, given \["1441", "Apple", "radar", "232", "plane"\] the function returns ("232", "radar","1441").

In [99]:
#INSERT YOUR ANSWER HERE.

elements = input("Enter word or numbers with spaces:").split()

def isSymmetrical (txt):
    return txt==(txt) [::-1]

def isSymmetricalTuple (elements):
    D1 = {}
    for i in elements:
        y1 = {i:str(isSymmetrical(i))}
        D1.update(y1)
        keys = []
        for (key, value) in D1.items():
            if value == 'True':
                keys.append(key)
    answer = print(keys[::-1])
    return answer

isSymmetricalTuple(elements)

Enter word or numbers with spaces: 1441 Apple radar 232 plane


['232', 'radar', '1441']


*****


### Question 2 **[80 pts]** :

**a)** **[15 pts]** Define a function called `minSubStr` that takes two string arguments ( S and T ), and returns `TRUE` if the characters of *T* exist in *S*, else returns `FALSE`. For example: given `S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'` and `T = "ABC"`, returns `TRUE` (`T = "ABCD"`, returns `FALSE)`


In [104]:
#INSERT YOUR ANSWER HERE.

S = 'xBxxxCxAxCxxBxxxxCxBxxxxBxCx'
T = "ABCD"

def miniSubStr(S,T):
    S1 = list(set(S))
    T1= list(set(T))
    for keys in T1:
        if S1.count(keys)==0:
            return False
    return True
         
print(miniSubStr(S,T))

False


**b)** **[15 pts]** Modify your `minSubStr` function defined in Q2.a to return the first possible substring (traversing from left) containing all the elements of `T`. For example: given `S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'` and `T = "ABC"`, returns **`"BxxAxxC"`**

In [3]:
#INSERT YOUR ANSWER HERE.

S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'
T = "ABC"

def miniSubStr(S,T):
    S1 = list(set(S))
    T1= list(set(T))
    for keys in T1:
        if S1.count(keys)==0:
            return False
    return True

def returnShortestSubStr(S,T):
    S1 = list(set(S))
    T1= list(set(T))
    
    min_str=S
    
    for ix,alphabet in enumerate(S):
        if alphabet in T1:
            sub_str=S[ix:]
            for pointer in range(len(sub_str)):
                if miniSubStr(sub_str[:pointer],T):
                    return sub_str[:pointer]
                    

returnShortestSubStr(S,T)

'BxxAxxC'

**c)** **[20 pts]** Modify your `minSubStr` function defined in Q2.b to return the shortest substring containing all the elements of T. For example: given `S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'` and `T = "ABC"`, returns **`"AxCxB"`**


In [1]:
#INSERT YOUR ANSWER HERE.

S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'
T = "ABC"

def miniSubStr(S,T):
    S1 = list(set(S))
    T1= list(set(T))
    for keys in T1:
        if S1.count(keys)==0:
            return False
    return True

def returnfirstSubStr(S,T):
    S1 = list(set(S))
    T1= list(set(T))
    
    min_str=S
    
    for ix,alphabet in enumerate(S):
        if alphabet in T1:
            start=S[ix:].find(alphabet)
            sub_str=S[start+ix:]
            for pointer in range(len(sub_str)):
                if miniSubStr(sub_str[:pointer],T):
                    if len(min_str)>len(sub_str[:pointer]):
                        min_str=sub_str[:pointer]
    return min_str
     
returnfirstSubStr(S,T)


'AxCxB'

**d)** **[30 pts]** modify your `minSubStr` function defined in Q2.c to return the shortest substring containing all the elements of T in order. For example: given `S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'` and `T = "ABC"`, returns **`"AxxBxC"`**

In [2]:
#INSERT YOUR ANSWER HERE.
S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'
T = "ABC"


def returnOrderedSubStr(S,T):
    T1= list((T))
    for ix,alphabet in enumerate(S):
        if alphabet == T1[0]:
            sub_str=S[ix:]
            found_point=0
            for pointer in range(len(sub_str)):
                if found_point==len(T1):
                    return sub_str[:pointer]
                if sub_str[pointer]==T1[found_point]:
                    found_point=found_point+1
                elif sub_str[pointer] in T1:
                    break
                
                    
returnOrderedSubStr(S,T)


'AxxBxC'

*****

### Question 3 **[30 pts]**:


**a)** Complete the given code to define three classes, Shape, Oval and Circle. 
- Shape will be the parent class of Oval and Circle. 
- Randomly create ten objects from Oval and Circle classes using the ``for`` loop given below
- Your code should produce correct number of Shapes, Circle and Oval objects. The count of objects should be calculated within the class definitions. 
  - Example output (note that since it is random every time it will be a different number of shapes) \\
  There are  10 random shape objects ['Circle', 'Circle', 'Circle', 'Circle', 'Oval', 'Circle', 'Oval', 'Oval', 'Circle', 'Circle'] \\
	 3 of them are ovals \\
	 7 of them are cirlces \\


In [58]:

#INSERT YOUR ANSWER HERE.
class Shape:
    def __init__(self,name):
        self.name = name

from random import choice
list_of_shapes = [choice(['Circle', 'Oval']) for x in range(10)]
for shape in list_of_shapes:
  if shape == 'Oval':
   class Shape:
    def __init__(self,name):
        self.name = Oval
    
  else:
    # create an object of circle class
   class Shape:
    def __init__(self,name):
        self.name = Circle

print(list_of_shapes)
print("Number of shape objects:",len(list_of_shapes))
print("Number of Oval objects:",list_of_shapes.count("Oval"))
print("Number of Circle objects:",list_of_shapes.count("Circle"))

['Circle', 'Oval', 'Oval', 'Circle', 'Circle', 'Oval', 'Oval', 'Oval', 'Oval', 'Oval']
Number of shape objects: 10
Number of Oval objects: 7
Number of Circle objects: 3


#### This is the end of assignment 2